routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'guest'], function () {
    Route::get('login', 'UserController@login')->name('login');
    Route::post('login', 'UserController@doLogin')->name('login.post');
});

Route::group(['prefix' => 'region', 'as' => 'region.'], function () {
    Route::get('villageAjax', 'RegionController@villageAjax');
    Route::get('villageAjax/{id}', 'RegionController@villageAjaxSingle');
});

Route::group(['middleware' => 'auth', 'prefix' => 'adm'], function () {
    Route::get('/', 'UserController@dashboard')->name('dashboard');
    Route::get('logout', 'UserController@logout')->name('logout');

    Route::group(['prefix' => 'usermanager', 'as' => 'usermanager.'], function () {
        Route::get('/', 'UserController@index')->name('index');
        Route::get('add', 'UserController@add')->name('add');
        Route::post('add', 'UserController@store')->name('add.post');
        Route::get('edit/{userId}', 'UserController@edit')->name('edit');
        Route::post('edit/{userId}', 'UserController@update')->name('edit.post');
        Route::get('delete/{userId}','UserController@delete')->name('delete');
    });

    Route::group(['prefix' => 'agentmanager', 'as' => 'agentmanager.'], function () {
        Route::get('/', 'AgentController@index')->name('index');
        Route::get('add', 'AgentController@add')->name('add');
        Route::post('add', 'AgentController@store')->name('add.post');
        Route::get('edit/{agentId}', 'AgentController@edit')->name('edit');
        Route::post('edit/{agentId}', 'AgentController@update')->name('edit.post');
        Route::get('delete/{agentId}', 'AgentController@delete')->name('delete');
        Route::get('add-user/{agentId}', 'AgentController@addUser')->name('add-user');
        Route::post('add-user/{agentId}', 'AgentController@storeUser')->name('add-user.post');
        Route::get('edit-user/{agentId}/{userId}', 'AgentController@editUser')->name('edit-user');
        Route::post('edit-user/{userId}', 'AgentController@updateUser')->name('edit-user.post');
        Route::get('add-driver/{agentId}', 'AgentController@addDriver')->name('add-driver');
        Route::post('add-driver/{agentId}', 'AgentController@storeDriver')->name('add-driver.post');
        Route::get('edit-driver/{agentId}/{userId}', 'AgentController@editDriver')->name('edit-driver');
        Route::get('add-courier/{agentId}', 'AgentController@addCourier')->name('add-courier');
        Route::post('add-courier/{agentId}', 'AgentController@storeCourier')->name('add-courier.post');
        Route::get('edit-courier/{agentId}/{userId}', 'AgentController@editCourier')->name('edit-courier');

        Route::get('show/{agentId}', 'AgentController@show')->name('show');
    });

    Route::group(['prefix' => 'drivermanager', 'as' => 'drivermanager.'], function () {
        Route::get('/', 'DriverController@index')->name('index');
    });
});

app/Models/Agent.php
<?php

namespace App\Models;

use App\Constants\AgentType;
use Eloquent;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use Wandxx\Support\Traits\UuidForKey;

/**
 * App\Models\Agent
 *
 * @property string $id
 * @property string $code
 * @property int|null $type
 * @property string $name
 * @property string $address
 * @property float|null $lat
 * @property float|null $lng
 * @property string|null $district_id
 * @property string $phone
 * @property string|null $phone2
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read mixed $type_text
 * @property-read Collection|Order[] $orders
 * @property-read int|null $orders_count
 * @property-read Collection|User[] $users
 * @property-read int|null $users_count
 * @method static Builder|Agent newModelQuery()
 * @method static Builder|Agent newQuery()
 * @method static Builder|Agent query()
 * @method static Builder|Agent whereAddress($value)
 * @method static Builder|Agent whereCode($value)
 * @method static Builder|Agent whereCreatedAt($value)
 * @method static Builder|Agent whereDistrictId($value)
 * @method static Builder|Agent whereId($value)
 * @method static Builder|Agent whereLat($value)
 * @method static Builder|Agent whereLng($value)
 * @method static Builder|Agent whereName($value)
 * @method static Builder|Agent wherePhone($value)
 * @method static Builder|Agent wherePhone2($value)
 * @method static Builder|Agent whereType($value)
 * @method static Builder|Agent whereUpdatedAt($value)
 * @mixin Eloquent
 * @property-read District|null $district
 * @property-read Collection|PickUp[] $pick_ups
 * @property-read int|null $pick_ups_count
 * @property string|null $village_id
 * @method static Builder|Agent whereVillageId($value)
 */
class Agent extends Model
{
    use UuidForKey;
    public $incrementing = false;
    protected $fillable = [
        'code', 'name', 'address',
        'village_id', 'phone', 'phone2',
        'lat', 'lng', 'type'
    ];
    protected $appends = ['type_text'];

    public function users()
    {
        return $this->belongsToMany(User::class)->withPivot(['status']);
    }

    public function couriers()
    {
        return $this->belongsToMany(User::class, 'agent_courier', 'agent_id', 'courier_id');
    }

    public function drivers()
    {
        return $this->belongsToMany(User::class, 'agent_driver', 'agent_id', 'driver_id');
    }

    public function village()
    {
        return $this->belongsTo(Village::class);
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function pick_ups()
    {
        return $this->hasMany(PickUp::class);
    }

    public function getTypeTextAttribute()
    {
        return !is_null($this->type) ? AgentType::label($this->type) : '-';
    }
}

app/Http/Controllers/AgentController.php
<?php

namespace App\Http\Controllers;

use App\Constants\AgentType;
use App\Contracts\AgentRepositoryContract;
use App\Contracts\RegionRepositoryContract;
use App\Contracts\UserRepositoryContract;
use App\Http\Requests\Agent\StoreAgentRequest;
use App\Http\Requests\Agent\UpdateAgentRequest;
use App\Http\Requests\User\StoreUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use DB;
use Exception;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Wandxx\Support\Constants\ActiveStatus;

class AgentController extends Controller
{
    private $_agentRepository;
    private $_userRepository;
    private $_regionRepository;

    public function __construct(AgentRepositoryContract $_agentRepository, UserRepositoryContract $_userRepository, RegionRepositoryContract $_regionRepository)
    {
        $this->_agentRepository = $_agentRepository;
        $this->_userRepository = $_userRepository;
        $this->_regionRepository = $_regionRepository;
    }

    public function index(Request $request): View
    {
        $agents = $this->_agentRepository->allAgent($request);
        return view('agent.index', compact('agents'));
    }

    public function add(): View
    {

        $types = AgentType::labels();
        return view('agent.add', compact('types'));
    }

    public function store(StoreAgentRequest $request): RedirectResponse
    {
        $this->_agentRepository->store($request->data());
        return redirect()->route('agentmanager.index')->with(['success' => 'Agent added.']);
    }

    public function edit(string $agentId): View
    {
        $agent = $this->_agentRepository->show($agentId);
        $types = AgentType::labels();
        $selected = $agent->village_id;
        return view('agent.edit', compact('agent', 'types', 'selected'));
    }

    public function show(string $agentId): View
    {
        $agent = $this->_agentRepository->show($agentId);
        return view('agent.show', compact('agent'));
    }

    public function update(UpdateAgentRequest $request, $agentId): RedirectResponse
    {
        $this->_agentRepository->update($request->data(), $agentId);
        return redirect()->route('agentmanager.index')->with(['success' => 'Agent updated.']);
    }

    public function delete(string $agentId): RedirectResponse
    {
        $this->_agentRepository->delete($agentId);
        return redirect()->route('agentmanager.index')->with(['success' => 'Agent deleted.']);
    }

    public function addUser(string $agentId): View
    {
        return view('agent.add_user');
    }

    public function editUser(string $agentId, string $userId): View
    {
        $agent = $this->_agentRepository->show($agentId);
        $user = $agent->users()->findOrFail($userId);
        return view('agent.edit_user', compact('user'));
    }

    public function storeUser(StoreUserRequest $request, string $agentId): RedirectResponse
    {
        DB::beginTransaction();

        try {
            $user = $this->_userRepository->store($request->data());
            $agent = $this->_agentRepository->show($agentId);
            $agent->users()->attach($user->id, ['status' => ActiveStatus::ACTIVE]);
            DB::commit();
            return redirect()->route('agentmanager.show', compact('agentId'))->with(['success' => 'User Added']);
        } catch (Exception $e) {
            DB::rollBack();
            return redirect()->route('agentmanager.show', compact('agentId'))->with(['success' => $e->getMessage()]);
        }
    }

    public function updateUser(UpdateUserRequest $request, string $userId): RedirectResponse
    {
        $this->_userRepository->update($request->data(), $userId);
        return back()->with(['success' => 'User Updated']);
    }

    public function addDriver(string $agentId): View
    {
        return view('agent.add_driver');
    }

    public function editDriver(string $agentId, string $userId): View
    {
        $agent = $this->_agentRepository->show($agentId);
        $user = $agent->drivers()->findOrFail($userId);
        return view('agent.edit_driver', compact('user'));
    }

    public function storeDriver(StoreUserRequest $request, string $agentId): RedirectResponse
    {
        DB::beginTransaction();

        try {
            $user = $this->_userRepository->store($request->data());
            $agent = $this->_agentRepository->show($agentId);
            $agent->drivers()->attach($user->id, ['status' => ActiveStatus::ACTIVE]);
            DB::commit();
            return redirect()->route('agentmanager.show', compact('agentId'))->with(['success' => 'User Added']);
        } catch (Exception $e) {
            DB::rollBack();
            return redirect()->route('agentmanager.show', compact('agentId'))->with(['success' => $e->getMessage()]);
        }
    }

    public function addCourier(string $agentId): View
    {
        return view('agent.add_courier');
    }

    public function editCourier(string $agentId, string $userId): View
    {
        $agent = $this->_agentRepository->show($agentId);
        $user = $agent->couriers()->findOrFail($userId);
        return view('agent.edit_courier', compact('user'));
    }

    public function storeCourier(StoreUserRequest $request, string $agentId): RedirectResponse
    {
        DB::beginTransaction();

        try {
            $user = $this->_userRepository->store($request->data());
            $agent = $this->_agentRepository->show($agentId);
            $agent->couriers()->attach($user->id, ['status' => ActiveStatus::ACTIVE]);
            DB::commit();
            return redirect()->route('agentmanager.show', compact('agentId'))->with(['success' => 'User Added']);
        } catch (Exception $e) {
            DB::rollBack();
            return redirect()->route('agentmanager.show', compact('agentId'))->with(['success' => $e->getMessage()]);
        }
    }

}

app/Http/Controllers/Api/AgentController.php
<?php

namespace App\Http\Controllers\Api;

use App\Contracts\AgentRepositoryContract;
use App\Contracts\OrderRepositoryContract;
use App\Contracts\PickUpRepositoryContract;
use App\Http\Controllers\Controller;
use App\Http\Requests\Agent\RequestPickUpRequest;
use App\Http\Requests\Api\Order\CreateOrderRequest;
use App\Transformers\Order\OrderTransformer;
use Dingo\Api\Http\Response;
use Dingo\Api\Routing\Helpers;
use Illuminate\Http\Request;

class AgentController extends Controller
{
    use Helpers;

    private $_agentRepository;
    private $_orderRepository;
    private $_pickUpRepository;

    public function __construct(AgentRepositoryContract $_agentRepository, OrderRepositoryContract $_orderRepository, PickUpRepositoryContract $_pickUpRepository)
    {
        $this->_agentRepository = $_agentRepository;
        $this->_orderRepository = $_orderRepository;
        $this->_pickUpRepository = $_pickUpRepository;
    }

    public function allOrder(Request $request): Response
    {
        $currentUser = $this->auth()->getUser();
        $agent = $this->_agentRepository->showAgentByUser($currentUser);
        $data = $this->_orderRepository->allByAgent($request, $agent);
        return $this->response()->paginator($data, new OrderTransformer());
    }

    public function showOrder(string $orderId): Response
    {
        $order = $this->_orderRepository->show($orderId);
        return $this->response()->item($order, new OrderTransformer());
    }

    public function createOrder(CreateOrderRequest $request): Response
    {
        $currentUser = $this->auth()->getUser();
        $agent = $this->_agentRepository->showAgentByUser($currentUser);
        $data = $this->_orderRepository->create($request->data(), $agent);
        return $this->response()->item($data, new OrderTransformer());
    }

    public function requestPickup(RequestPickUpRequest $request): Response
    {
        $currentUser = $this->auth()->getUser();
        $agent = $this->_agentRepository->showAgentByUser($currentUser);
        $this->_pickUpRepository->requestPickup($request->data(), $agent);
        return $this->response()->created();
    }
}

resources/views/agent/add.blade.php
@extends('layouts.base')
@section('title','GTPro | Agent Manager | Add')
@section('page_header_title','Add Agent')
@push('contents')
    <div class="row">
        <div class="col-sm-6">
            <div class="box box-solid">
                <div class="box-body">
                    {!! Form::open(['class'=>'form-horizontal','autocomplete'=>'off']) !!}
                    @include('agent.form')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endpush

resources/views/agent/add_courier.blade.php
@extends('layouts.base')
@section('title','GTPro | User Manager | Add')
@section('page_header_title','Add User')
@push('contents')
    <div class="row">
        <div class="col-sm-6">
            <div class="box box-solid">
                <div class="box-body">
                    {!! Form::open(['class'=>'form-horizontal','autocomplete'=>'off']) !!}
                    {!! Form::hidden('roles[]',config('gtpro.courier_id')) !!}
                    @include('agent.form_user')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>


@endpush

resources/views/agent/add_driver.blade.php
@extends('layouts.base')
@section('title','GTPro | User Manager | Add')
@section('page_header_title','Add User')
@push('contents')
    <div class="row">
        <div class="col-sm-6">
            <div class="box box-solid">
                <div class="box-body">
                    {!! Form::open(['class'=>'form-horizontal','autocomplete'=>'off']) !!}
                    {!! Form::hidden('roles[]',config('gtpro.driver_id')) !!}
                    @include('agent.form_user')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>


@endpush

resources/views/agent/add_user.blade.php
@extends('layouts.base')
@section('title','GTPro | User Manager | Add')
@section('page_header_title','Add User')
@push('contents')
    <div class="row">
        <div class="col-sm-6">
            <div class="box box-solid">
                <div class="box-body">
                    {!! Form::open(['class'=>'form-horizontal','autocomplete'=>'off']) !!}
                    {!! Form::hidden('roles[]',config('gtpro.agent_warehouse_id')) !!}
                    @include('agent.form_user')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>


@endpush

resources/views/agent/edit.blade.php
@extends('layouts.base')
@section('title','GTPro | Agent Manager | Edit')
@section('page_header_title','Edit Agent')
@push('contents')
    <div class="row">
        <div class="col-sm-6">
            <div class="box box-solid">
                <div class="box-body">
                    {!! Form::model($agent,['class'=>'form-horizontal','autocomplete'=>'off']) !!}
                    @include('agent.form')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endpush

@push('heads')
    <script>
        var $selectedVillage = {{ $selected ?? "" }};
    </script>
@endpush

resources/views/agent/edit_courier.blade.php
@extends('layouts.base')
@section('title','GTPro | User Manager | Edit')
@section('page_header_title','Edit User')
@push('contents')
    <div class="row">
        <div class="col-sm-6">
            <div class="box box-solid">
                <div class="box-body">
                    {!! Form::model($user,['class'=>'form-horizontal','autocomplete'=>'off','route' => ['agentmanager.edit-user.post','userId'=>$user->id]]) !!}
                    {!! Form::hidden('roles[]',config('gtpro.courier_id')) !!}
                    @include('agent.form_user')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>


@endpush

resources/views/agent/index.blade.php
@extends('layouts.base')
@section('title','GTPro | Agent Manager')
@section('page_header_title')
    Agent Manager &nbsp; <a href="{{ route('agentmanager.add') }}" class="btn btn-success btn-xs"><i
                class="fa fa-plus"></i> Add</a>
@stop

@push('contents')
    <div class="box box-solid">
        <div class="box-body">
            <table class="table">
                <thead>
                <tr>
                    <th>Action</th>
                    <th>Code</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Phone</th>
                    <th>Type</th>
                </tr>
                </thead>
                <tbody>
                @forelse($agents as $agent)
                    <tr>
                        <td>
                            <a href="{{ route('agentmanager.edit',['agentId' => $agent->id]) }}"
                               class="btn btn-success btn-xs"><i class="fa fa-pencil"></i></a>
                            <a onclick="return confirm('Delete user?')"
                               href="{{ route('agentmanager.delete',['agentId' => $agent->id]) }}"
                               class="btn btn-success btn-xs"><i class="fa fa-trash"></i></a>
                            <a class="btn btn-success btn-xs"
                               href="{{ route('agentmanager.show',['agentId'=>$agent->id]) }}"><i
                                        class="fa fa-eye"></i></a>
                        </td>
                        <td>{{ $agent->code }}</td>
                        <td>{{ $agent->name }}</td>
                        <td>{{ $agent->address }}</td>
                        <td>{{ $agent->phone }}</td>
                        <td>{{ $agent->type_text }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="6" class="text-center">No Data</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
            <div class="text-right">
                {!! $agents->render() !!}
            </div>
        </div>
    </div>
@endpush

resources/views/agent/show.blade.php
@extends('layouts.base')
@section('title','GTPro | Agent Manager | Show')
@section('page_header_title','Show Agent')
@push('contents')
    <div class="row">
        <div class="col-sm-6">
            <div class="box box-solid">
                <div class="box-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            {!! Form::label('code','Code',['class'=>'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                <div class="form-control-static">{{ $agent->code }}</div>
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('type','Type',['class'=>'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                <div class="form-control-static">{{ \App\Constants\AgentType::label($agent->type) }}</div>
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('name','Name',['class'=>'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                <div class="form-control-static">{{ $agent->name }}</div>
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('address','Address',['class'=>'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                <div class="form-control-static">{{ $agent->address }}</div>
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('lat','Latitude',['class'=>'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                <div class="form-control-static">{{ $agent->lat }}</div>
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('lng','Longitude',['class'=>'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                <div class="form-control-static">{{ $agent->lng }}</div>
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('phone','Phone',['class'=>'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                <div class="form-control-static">{{ $agent->phone }}</div>
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('phone2','Phone 2',['class'=>'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                <div class="form-control-static">{{ $agent->phone2 ?? '-' }}</div>
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('village','Village',['class'=>'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                <div class="form-control-static">{{ $agent->village->name ?? '-' }}</div>
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('district','District',['class'=>'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                <div class="form-control-static">{{ $agent->village->district->name ?? '-' }}</div>
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('regency','Regency',['class'=>'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                <div class="form-control-static">{{ $agent->village->district->regency->name ?? '-' }}</div>
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('province','Province',['class'=>'control-label col-sm-4']) !!}
                            <div class="col-sm-8">
                                <div class="form-control-static">{{ $agent->village->district->regency->province->name ?? '-' }}</div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="box box-success box-solid">
                <div class="box-header">
                    <h3 class="box-title">User</h3>
                </div>
                <div class="box-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Action</th>
                            <th>Name</th>
                            <th>Email</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($agent->users()->get() as $user)
                            <tr>
                                <td>
                                    <a href="{{ route('agentmanager.edit-user',['userId'=>$user->id,'agentId'=>$agent->id]) }}"
                                       class="btn btn-success btn-xs"><i class="fa fa-pencil"></i></a>
                                    <a onclick="return confirm('Delete user?')"
                                       href="{{ route('usermanager.delete',['userId'=>$user->id]) }}"
                                       class="btn btn-success btn-xs"><i class="fa fa-trash"></i></a>
                                </td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="3" class="text-center">No User</td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                    <div class="text-right">
                        <a href="{{ route('agentmanager.add-user',['agentId'=>$agent->id]) }}"
                           class="btn btn-success">Add User</a>
                    </div>
                </div>
            </div>
        </div>
        @if($agent->type == \App\Constants\AgentType::WAREHOUSE)
            <div class="col-sm-6">
                <div class="box box-success box-solid">
                    <div class="box-header">
                        <h3 class="box-title">Driver</h3>
                    </div>
                    <div class="box-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Action</th>
                                <th>Name</th>
                                <th>Email</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($agent->drivers()->get() as $user)
                                <tr>
                                    <td>
                                        <a href="{{ route('agentmanager.edit-driver',['userId'=>$user->id,'agentId'=>$agent->id]) }}"
                                           class="btn btn-success btn-xs"><i class="fa fa-pencil"></i></a>
                                        <a onclick="return confirm('Delete user?')"
                                           href="{{ route('usermanager.delete',['userId'=>$user->id]) }}"
                                           class="btn btn-success btn-xs"><i class="fa fa-trash"></i></a>
                                    </td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="3" class="text-center">No User</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                        <div class="text-right">
                            <a href="{{ route('agentmanager.add-driver',['agentId'=>$agent->id]) }}"
                               class="btn btn-success">Add Driver</a>
                        </div>
                    </div>
                </div>

                <div class="box box-success box-solid">
                    <div class="box-header">
                        <h3 class="box-title">Courier</h3>
                    </div>
                    <div class="box-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Action</th>
                                <th>Name</th>
                                <th>Email</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($agent->couriers()->get() as $user)
                                <tr>
                                    <td>
                                        <a href="{{ route('agentmanager.edit-courier',['userId'=>$user->id,'agentId'=>$agent->id]) }}"
                                           class="btn btn-success btn-xs"><i class="fa fa-pencil"></i></a>
                                        <a onclick="return confirm('Delete user?')"
                                           href="{{ route('usermanager.delete',['userId'=>$user->id]) }}"
                                           class="btn btn-success btn-xs"><i class="fa fa-trash"></i></a>
                                    </td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="3" class="text-center">No User</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                        <div class="text-right">
                            <a href="{{ route('agentmanager.add-courier',['agentId'=>$agent->id]) }}"
                               class="btn btn-success">Add Courier</a>
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endpush