routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'guest'], function () {
    Route::get('login', 'UserController@login')->name('login');
    Route::post('login', 'UserController@doLogin')->name('login.post');
});

Route::group(['prefix' => 'region', 'as' => 'region.'], function () {
    Route::get('villageAjax', 'RegionController@villageAjax');
    Route::get('villageAjax/{id}', 'RegionController@villageAjaxSingle');
});

Route::group(['middleware' => 'auth', 'prefix' => 'adm'], function () {
    Route::get('/', 'UserController@dashboard')->name('dashboard');
    Route::get('logout', 'UserController@logout')->name('logout');

    Route::group(['prefix' => 'usermanager', 'as' => 'usermanager.'], function () {
        Route::get('/', 'UserController@index')->name('index');
        Route::get('add', 'UserController@add')->name('add');
        Route::post('add', 'UserController@store')->name('add.post');
        Route::get('edit/{userId}', 'UserController@edit')->name('edit');
        Route::post('edit/{userId}', 'UserController@update')->name('edit.post');
        Route::get('delete/{userId}','UserController@delete')->name('delete');
    });

    Route::group(['prefix' => 'agentmanager', 'as' => 'agentmanager.'], function () {
        Route::get('/', 'AgentController@index')->name('index');
        Route::get('add', 'AgentController@add')->name('add');
        Route::post('add', 'AgentController@store')->name('add.post');
        Route::get('edit/{agentId}', 'AgentController@edit')->name('edit');
        Route::post('edit/{agentId}', 'AgentController@update')->name('edit.post');
        Route::get('delete/{agentId}', 'AgentController@delete')->name('delete');
        Route::get('add-user/{agentId}', 'AgentController@addUser')->name('add-user');
        Route::post('add-user/{agentId}', 'AgentController@storeUser')->name('add-user.post');
        Route::get('edit-user/{agentId}/{userId}', 'AgentController@editUser')->name('edit-user');
        Route::post('edit-user/{userId}', 'AgentController@updateUser')->name('edit-user.post');
        Route::get('add-driver/{agentId}', 'AgentController@addDriver')->name('add-driver');
        Route::post('add-driver/{agentId}', 'AgentController@storeDriver')->name('add-driver.post');
        Route::get('edit-driver/{agentId}/{userId}', 'AgentController@editDriver')->name('edit-driver');
        Route::get('add-courier/{agentId}', 'AgentController@addCourier')->name('add-courier');
        Route::post('add-courier/{agentId}', 'AgentController@storeCourier')->name('add-courier.post');
        Route::get('edit-courier/{agentId}/{userId}', 'AgentController@editCourier')->name('edit-courier');

        Route::get('show/{agentId}', 'AgentController@show')->name('show');
    });

    Route::group(['prefix' => 'drivermanager', 'as' => 'drivermanager.'], function () {
        Route::get('/', 'DriverController@index')->name('index');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Eloquent;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\DatabaseNotification;
use Illuminate\Notifications\DatabaseNotificationCollection;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Carbon;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Traits\HasRoles;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Wandxx\Support\Constants\ActiveStatus;
use Wandxx\Support\Traits\UuidForKey;

/**
 * App\Models\User
 *
 * @property string $id
 * @property string $name
 * @property string $email
 * @property Carbon|null $email_verified_at
 * @property string $password
 * @property int $status
 * @property mixed|null $metadata
 * @property string|null $remember_token
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read Collection|Agent[] $agents
 * @property-read int|null $agents_count
 * @property-read mixed $status_text
 * @property-read DatabaseNotificationCollection|DatabaseNotification[] $notifications
 * @property-read int|null $notifications_count
 * @property-read Collection|Permission[] $permissions
 * @property-read int|null $permissions_count
 * @property-read Collection|Role[] $roles
 * @property-read int|null $roles_count
 * @method static Builder|User newModelQuery()
 * @method static Builder|User newQuery()
 * @method static Builder|User permission($permissions)
 * @method static Builder|User query()
 * @method static Builder|User role($roles, $guard = null)
 * @method static Builder|User whereCreatedAt($value)
 * @method static Builder|User whereEmail($value)
 * @method static Builder|User whereEmailVerifiedAt($value)
 * @method static Builder|User whereId($value)
 * @method static Builder|User whereMetadata($value)
 * @method static Builder|User whereName($value)
 * @method static Builder|User wherePassword($value)
 * @method static Builder|User whereRememberToken($value)
 * @method static Builder|User whereStatus($value)
 * @method static Builder|User whereUpdatedAt($value)
 * @mixin Eloquent
 */
class User extends Authenticatable implements JWTSubject
{
    use Notifiable, HasRoles, UuidForKey;

    public $incrementing = false;
    protected $fillable = [
        'name', 'email', 'password', 'status'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $appends = [
        'status_text'
    ];

    protected static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $model->password = bcrypt($model->password);
        });
    }

    public function agents()
    {
        return $this->belongsToMany(Agent::class)->withPivot('status');
    }

    public function getStatusTextAttribute()
    {
        return ActiveStatus::label($this->status) ?? '-';
    }

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        return [];
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Contracts\UserRepositoryContract;
use App\Http\Controllers\Controller;
use App\Http\Requests\Api\LoginRequest;
use App\Transformers\AuthTransformer;
use App\Transformers\UserTransformer;
use Dingo\Api\Http\Response;
use Dingo\Api\Routing\Helpers;
use JWTAuth;

class UserController extends Controller
{
    use Helpers;

    private $_userRepository;

    public function __construct(UserRepositoryContract $_userRepository)
    {
        $this->_userRepository = $_userRepository;
    }

    public function profile(): Response
    {
        $user = $this->_userRepository->show(auth()->id());
        return $this->response()->item($user, new UserTransformer());
    }

    public function login(LoginRequest $request): Response
    {
        if (!$token = JWTAuth::attempt($request->data())) {
            $this->response()->error('Credential not match.', 401);
        }

        $data = collect(compact('token'));
        return $this->response()->item($data, new AuthTransformer());
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Contracts\UserRepositoryContract;
use App\Http\Requests\User\StoreUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Http\Requests\User\UserLoginRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    private $_userRepository;

    public function __construct(UserRepositoryContract $_userRepository)
    {
        $this->_userRepository = $_userRepository;
    }

    public function login(): View
    {
        return view('login');
    }

    public function doLogin(UserLoginRequest $request): RedirectResponse
    {
        if (!auth()->attempt($request->data(), $request->remember())) {
            return back()->with(['error' => 'Credential not match.']);
        }

        return redirect()
            ->route('dashboard')
            ->with(['success' => sprintf('Welcome back %s', auth()->user()->name)]);
    }

    public function dashboard(): View
    {
        return view('adm.dashboard');
    }

    public function logout(): RedirectResponse
    {
        auth()->logout();
        return redirect()->route('login')->with(['success' => 'Logged out succesfully.']);
    }

    public function index(Request $request)
    {
        $users = $this->_userRepository->allUser($request);
        return view('user.index', compact('users'));
    }

    public function add(): View
    {
        $roles = Role::all();
        return view('user.add', compact('roles'));
    }

    public function edit(string $userId): View
    {
        $roles = Role::all();
        $user = $this->_userRepository->show($userId);
        return view('user.edit', compact('roles', 'user'));
    }

    public function show(string $userId)
    {
        $user = $this->_userRepository->show($userId);
        return view('user.show', compact('user'));
    }

    public function store(StoreUserRequest $request): RedirectResponse
    {
        $this->_userRepository->store($request->data());
        return redirect()->route('usermanager.index')->with(['success' => 'User added.']);
    }

    public function update(UpdateUserRequest $request, $userId): RedirectResponse
    {
        $this->_userRepository->update($request->data(), $userId);
        return redirect()->route('usermanager.index')->with(['success' => 'User updated.']);
    }

    public function delete(string $userId): RedirectResponse
    {
        $this->_userRepository->delete($userId);
        return back()->with(['success' => 'User deleted.']);
    }

    public function updateProfile(StoreUserRequest $request): RedirectResponse
    {
        $this->_userRepository->updateProfile($request->data(), auth()->id());
        return back();
    }
}

resources/views/user/add.blade.php
@extends('layouts.base')
@section('title','GTPro | User Manager | Add')
@section('page_header_title','Add User')
@push('contents')
    <div class="row">
        <div class="col-sm-6">
            <div class="box box-solid">
                <div class="box-body">
                    {!! Form::open(['class'=>'form-horizontal','autocomplete'=>'off']) !!}
                    @include('user.form')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>


@endpush

resources/views/user/edit.blade.php
@extends('layouts.base')
@section('title','GTPro | User Manager | Edit')
@section('page_header_title','Edit User')
@push('contents')
    <div class="row">
        <div class="col-sm-6">
            <div class="box box-solid">
                <div class="box-body">
                    {!! Form::model($user,['class'=>'form-horizontal','autocomplete'=>'off']) !!}
                    @include('user.form')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>


@endpush

resources/views/user/form.blade.php
<div class="form-group">
    {!! Form::label('name','Name',['class'=>'control-label col-sm-4']) !!}
    <div class="col-sm-8">
        {!! Form::text('name',null,['class'=>'form-control']) !!}
    </div>
</div>

<div class="form-group">
    {!! Form::label('email','Email',['class'=>'control-label col-sm-4']) !!}
    <div class="col-sm-8">
        {!! Form::text('email',null,['class'=>'form-control']) !!}
    </div>
</div>

<div class="form-group">
    {!! Form::label('password','Password',['class'=>'control-label col-sm-4']) !!}
    <div class="col-sm-8">
        {!! Form::password('password',['class'=>'form-control']) !!}
    </div>
</div>

<div class="form-group">
    {!! Form::label('password_confirmation','Confirm Password',['class'=>'control-label col-sm-4']) !!}
    <div class="col-sm-8">
        {!! Form::password('password_confirmation',['class'=>'form-control']) !!}
    </div>
</div>

<div class="form-group">
    {!! Form::label('status','Status',['class'=>'control-label col-sm-4']) !!}
    <div class="col-sm-8">
        <div style="margin-top: 10px">
            <div><label>{!! Form::checkbox('status',1,isset($user) ? $user->status == 1:false) !!} active</label></div>
        </div>
    </div>
</div>

<div class="form-group">
    {!! Form::label('roles','Roles',['class'=>'control-label col-sm-4']) !!}
    <div class="col-sm-8">
        {!! Form::select('roles[]',$roles->pluck('name','id'),isset($user) ? $user->roles->first()->id:null,['class'=>'form-control','placeholder'=>'Select Role']) !!}
    </div>
</div>
<div class="form-group">
    <div class="col-sm-12">
        <div class="text-right">
            <button type="submit" class="btn btn-success">Save</button>
        </div>
    </div>
</div>

resources/views/user/index.blade.php
@extends('layouts.base')
@section('title','GTPro | User Manager')
@section('page_header_title')
    User Manager &nbsp; <a href="{{ route('usermanager.add') }}" class="btn btn-success btn-xs"><i class="fa fa-plus"></i> Add</a>
@stop

@push('contents')
    <div class="box box-solid">
        <div class="box-body">
            <table class="table">
                <thead>
                <tr>
                    <th>Action</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th>Roles</th>
                </tr>
                </thead>
                <tbody>
                @forelse($users as $user)
                    <tr>
                        <td>
                            @if(auth()->id() != $user->id)
                            <a href="{{ route('usermanager.edit',['userId' => $user->id]) }}" class="bt btn-success btn-xs"><i class="fa fa-pencil"></i></a>
                            <a onclick="return confirm('Delete user?')" href="{{ route('usermanager.delete',['userId' => $user->id]) }}" class="bt btn-success btn-xs"><i class="fa fa-trash"></i></a>
                            @endif
                        </td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->status_text }}</td>
                        <td>{{ implode(', ',$user->roles->pluck('name')->toArray()) }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5" class="text-center">No Data</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
            <div class="text-right">
                {!! $users->render() !!}
            </div>
        </div>
    </div>
@endpush